blank_issues_enabled: false
contact_links:
  - name: Aurora Project Board
    url: https://github.com/orgs/gccloudone-aurora/projects/1
    about: View the org-wide Aurora roadmap, backlog, and sprint views.
