name: Epic
description: Track a high-level deliverable in Aurora (with sub-issues for progress).
title: "[Epic] <short summary here>"
labels: [epic]
body:
  - type: markdown
    attributes:
      value: |
        🔖 Please follow our [Issue & PR Naming Conventions](https://aurora.gccloudone.alpha.canada.ca/team/standard-operating-procedures/issue-naming/).

  - type: textarea
    id: summary
    attributes:
      label: Epic Summary
      description: Short, outcome-oriented description of this epic and its purpose.
      placeholder: Integrate Chainguard into GC Secure Artifacts.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define measurable conditions for completion of this epic.
      placeholder: |
        - [ ] All workloads migrated to Workload Identity
        - [ ] Documentation updated in TechDocs
        - [ ] Cluster add-ons redeployed without downtime

  - type: input
    id: quarter
    attributes:
      label: Target Quarter
      description: Planned quarter (e.g., Q4 2025, Q1 2026). This will map to the Aurora Project iteration.
      placeholder: Q4 2025

  - type: input
    id: client
    attributes:
      label: Client / Partner
      description: Department, SSC Field, or Project Team this epic benefits (e.g., STC, SSC-Aurora).
      placeholder: STC
