name: Epic
description: Track a high-level deliverable in Aurora (with sub-issues for progress).
title: "[Epic]: "
labels: [epic]
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Summary
        Provide a short description of this Epic and its purpose.

  - type: input
    id: quarter
    attributes:
      label: Target Quarter
      description: Planned quarter (e.g., Q4 2025, Q1 2026).
      placeholder: Q4 2025

  - type: input
    id: client
    attributes:
      label: Client / Partner
      description: Department, SSC field, or team this Epic benefits.
      placeholder: STC

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: What business or technical value does this Epic deliver?
      placeholder: Shared trusted images reduce duplication and cost.

  - type: textarea
    id: tasks
    attributes:
      label: Tasks (sub-issues)
      description: Use `- [ ] #issue_number` to link tasks; progress shows inside this Epic.
      placeholder: |
        - [ ] #123 Sub-issue 1
        - [ ] #124 Sub-issue 2
        - [ ] #125 Sub-issue 3
