name: Release Helm Charts

on:
  push:
    branches:
      - $default-branch

permissions:
  contents: write

jobs:
  release-helm:
    uses: gccloudone-aurora/.github/.github/workflows/release-helm.yaml@v1
